version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo Nothing to do yet
artifact:
  files:
    - index.html
    - favicom.ico
    - styles/main.css
    - images/*