AWSTemplateFormatVersion: '2010-09-09'
Description: Sam deployment for portfolio
Resources:
  PrtFolioFunction:
    Properties:
      CodeUri: s3://portfoliobuild.prathveerrai.info/bad71514bedd752a7cf9eda4ac418f33
      Handler: lambda_handler.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::356227741561:role/LambdaS3Access
      Runtime: python3.7
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
